# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  private_lane :clean_build do |options|
    sh("rm","-rf",".build")
    clean_build_artifacts()
    clear_derived_data(derived_data_path: "./DerivedData")
  end

  lane :test_SwiftySimpleKeychain do
  
  clean_build

  spm(
    command: "build",
    build_path: "./build",
    configuration: "release"
  )

  scan(
    project: "./SwiftySimpleKeychain.xcodeproj",
    devices: ["iPhone 8"],
    code_coverage: true,
    scheme: "SwiftySimpleKeychain-Package",
    output_directory: "docs/fastlane/reports",
    output_types: "html"
  )
  end

end
